services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    env_file: 'stack.env'
    container_name: audiobookshelf
    ports:
      - ${AUDIOBOOKSHELF_PORT}:80
    volumes:
      - ${MOUNT_POINT}/Media/Books:/audiobooks
      - ${MOUNT_POINT_BOOKS_CONFIG}:/config
      - ${MOUNT_POINT}/Media/Books/audiobookshelf-metadata:/metadata
    restart: unless-stopped