services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    env_file: '.env'
    container_name: audiobookshelf
    ports:
      - ${AUDIOBOOKSHELF_PORT}:80
    volumes:
      - ${MOUNT_POINT}/Media/Books:/audiobooks
      - ${APP_CONFIG}/audiobookshelf:/config
      - ${MOUNT_POINT}/Media/Books/audiobookshelf-metadata:/metadata
    restart: unless-stopped