services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - ${AUDIOBOOKSHELF_PORT}:80
    volumes:
      - ${MOUNT_POINT_BOOKS}:/audiobooks
      - ${MOUNT_POINT_BOOKS_CONFIG}:/config
      - ${MOUNT_POINT_BOOKS_METADATA}:/metadata
    env_file:
      - stack.env
