services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - ${MOUNT_POINT}/Media/Books:/audiobooks
      - /home/bobby/.config/audiobookshelf:/config
      - ${MOUNT_POINT}Media/Books/Audiobookshelf-metadatia:/metadata
    env_file:
      - stack.env
