services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /mnt/legion/Media/Books:/audiobooks
      - /home/bobby/.config/audiobookshelf:/config
      - /mnt/legion/Media/Books/Audiobookshelf-metadatia:/metadata
