services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    env_file: '.env'
    container_name: audiobookshelf
    user: 1000:1000
    ports:
      - ${AUDIOBOOKSHELF_PORT}:80
    volumes:
      - ${MOUNT_POINT}/Media/Books:/audiobooks
      - ${APP_CONFIG}/audiobookshelf:/config
      - ${MOUNT_POINT}/Media/Books/audiobookshelf-metadata:/metadata
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  jellyfin:
    image: jellyfin/jellyfin:latest
    env_file: '.env'
    container_name: jellyfin
    user: 0:0
    network_mode: host
    ports:
      - ${JELLYFIN_PORT}:8096
    volumes:
      - ${JELLY_LOCATION}/config:/config
      - ${JELLY_LOCATION}/cache:/cache
      - ${MOUNT_POINT}/Media:/media
      - ${MOUNT_POINT}/Media2:/media2
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
  
  prowlarr:
    image: linuxserver/prowlarr:latest
    env_file: '.env'
    container_name: prowlarr
    user: 1000:1000
    network_mode: "service:gluetun"
    volumes:
      - ${APP_CONFIG}/Prowlarr/config:/config
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    env_file: '.env'
    container_name: sonarr
    user: 1000:1000
    network_mode: "service:gluetun"
    volumes:
      - ${APP_CONFIG}/Sonarr/config:/config
      - ${MOUNT_POINT}/Media:/data/media
      - ${MOUNT_POINT}/Media2:/data/media2
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    env_file: '.env'
    container_name: radarr
    user: 1000:1000
    network_mode: "service:gluetun"
    volumes:
      - ${APP_CONFIG}/Radarr/config:/config
      - ${MOUNT_POINT}/Media:/data/media
      - ${MOUNT_POINT}/Media2:/data/media2
    restart: unless-stopped
  
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    env_file: '.env'
    container_name: homarr
    user: 0:0
    ports:
      - ${HOMARR_PORT}:7575
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOMARR_PATH}/configs:/app/data/configs
      - ${HOMARR_PATH}/icons:/app/public/icons
      - ${HOMARR_PATH}/data:/data
      - ${HOMARR_PATH}/appdata:/appdata
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    env_file: '.env'
    container_name: bazarr
    user: 1000:1000
    network_mode: "service:gluetun"
    volumes:
      - ${APP_CONFIG}/Bazarr/config:/config
      - ${MOUNT_POINT}/Media:/data/media
      - ${MOUNT_POINT}/Media2:/data/media2
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    env_file: '.env'
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - ${APP_CONFIG}/qbittorrent/config:/config
      - ${MOUNT_POINT}/Media2/torrent:/data/torrent
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    env_file: '.env'
    container_name: jellyseerr
    user: 0:0
    ports:
      - ${JELLYSEER_PORT}:5055
    volumes:
      - ${APP_CONFIG}/Jellyseer/config:/app/config
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun:latest
    env_file: '.env'
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - ${TORRENTING_PORT}:${TORRENTING_PORT}
      - ${TORRENTING_PORT}:${TORRENTING_PORT}/udp
      - ${WEBUI_PORT}:${WEBUI_PORT}
      - ${PROWLARR_PORT}:9696
      - ${SONARR_PORT}:8989
      - ${RADARR_PORT}:7878
      - ${BAZARR_PORT}:6767
    volumes:
      - ${APP_CONFIG}/gluetun/config:/gluetun