services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    env_file: '.env'
    container_name: audiobookshelf
    ports:
      - ${AUDIOBOOKSHELF_PORT}:80
    volumes:
      - ${MOUNT_POINT}/Media/Books:/audiobooks
      - ${APP_CONFIG}/audiobookshelf:/config
      - ${MOUNT_POINT}/Media/Books/audiobookshelf-metadata:/metadata
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  jellyfin:
    image: jellyfin/jellyfin:latest
    env_file: '.env'
    container_name: jellyfin
    user: 0:0
    network_mode: host
    ports:
      - ${JELLYFIN_PORT}:8096
    volumes:
      - ${JELLYFIN_CONFIG_DIR}:/config
      - ${JELLYFIN_CACHE_DIR}:/cache
      - ${JELLYFIN_DATA_DIR}:/data
      - ${JELLYFIN_LOG_DIR}:/log
      - ${MOUNT_POINT}/Media:/media
      - ${MOUNT_POINT}/Media2:/media2
    restart: unless-stopped
  
  prowlarr:
    image: linuxserver/prowlarr:latest
    env_file: '.env'
    container_name: prowlarr
    hostname: prowlarr
    user: 0:0
    ports:
      - ${PROWLARR_PORT}:9696
    volumes:
      - ${APP_CONFIG}/Prowlarr/config:/config
      - ${ARRPATH}/Apps/Prowlarr:/data/Backup
      - ${ARRPATH}:/downloads
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    env_file: '.env'
    container_name: sonarr
    hostname: sonarr
    user: 0:0
    ports:
      - ${SONARR_PORT}:8989
    volumes:
      - ${APP_CONFIG}/Sonarr/config:/config
      - ${ARRPATH}/Apps/Sonarr:/data/Backup
      - ${MOUNT_POINT}/Media/TV_Shows:/data/tvshows
      - ${MOUNT_POINT}/Media2/TV_Shows:/data/tvshows2
      - ${ARRPATH}:/downloads
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    env_file: '.env'
    container_name: radarr
    hostname: radarr
    user: 0:0
    ports:
      - ${RADARR_PORT}:7878
    volumes:
      - ${APP_CONFIG}/Radarr/config:/config
      - ${ARRPATH}/Apps/Radarr:/data/Backup
      - ${MOUNT_POINT}/Media/Movies:/data/movies
      - ${MOUNT_POINT}/Media2/Movies:/data/movies2
      - ${ARRPATH}:/downloads
    restart: unless-stopped
  
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    user: 0:0
    ports:
      - ${HOMARR_PORT}:7575
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ARRPATH}/Apps/Homarr/configs:/app/data/configs
      - ${ARRPATH}/Apps/Homarr/icons:/app/public/icons
      - ${ARRPATH}/Apps/Homarr/data:/data
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    env_file: '.env'
    container_name: qbittorrent
    hostname: qbittorrent
    restart: unless-stopped
    volumes:
      - ${APP_CONFIG}/qbittorrent/config:/config
      - ${ARRPATH}:/downloads
    ports:
      - ${WEBUI_PORT}:${WEBUI_PORT}
      - ${TORRENTING_PORT}:${TORRENTING_PORT}
      - ${TORRENTING_PORT}:${TORRENTING_PORT}/udp