# remember to copy this file into the /gluetun/auth/config.yoml later.
[[roles]]
name = "satyapraneet63/gsp-qbittorent-gluetun-sync-port-mod-arm64"
routes = ["GET /v1/openvpn/portforwarded"]
auth = "apikey"
apikey = "M8jPStro7iMiCMLQUTSTfh"