[[roles]]
name = "t-anc/GSP-Qbittorent-Gluetun-sync-port-mod"
routes = ["GET /v1/openvpn/portforwarded"]
auth = "apikey"
# This is an example apikey, generate your own.
apikey = "M8jPStro7iMiCMLQUTSTfh"
