services:
  jellyfin:
    image: jellyfin/jellyfin
    env_file: 'stack.env'
    container_name: jellyfin
    user: 106:112
    network_mode: host
    ports:
      - ${JELLYFIN_PORT}:80
    volumes:
      - ${JELLYFIN_CONFIG_DIR}:/config
      - ${JELLYFIN_CACHE_DIR}:/cache
      - ${JELLYFIN_DATA_DIR}:/data
      - ${JELLYFIN_LOG_DIR}:/log
      - /mnt/legion/Media:/media
      - /mnt/legion/Media2:/media2
    restart: unless-stopped
    #extra_hosts:
    #  - 'host.docker.internal:host-gateway'