services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    env_file: '.env'
    container_name: prowlarr
    hostname: prowlarr
    ports:
      - ${PROWLARR_PORT}:9696
    volumes:
      - ${APP_CONFIG}/Prowlarr/config:/config
      - ${ARRPATH}/Apps/Prowlarr:/data/Backup
      - ${ARRPATH}:/downloads
    restart: unless-stopped