services:
  radarr:
    image: linuxserver/radarr:latest
    env_file: '.env'
    container_name: radarr
    hostname: radarr
    ports:
      - ${RADARR_PORT}:7878
    volumes:
      - ${APP_CONFIG}/Radarr/config:/config
      - ${ARRPATH}/Apps/Radarr:/data/Backup
      - ${MOUNT_POINT}/Media/Movies:/data/movies
      - ${MOUNT_POINT}/Media2/Movies:/data/movies2
      - ${ARRPATH}:/downloads
    restart: unless-stopped